pull_request_rules:
  - name: automatic backport of common pages
    conditions:
      - base=rolling
      - "files~=Governance|Contact|index|Marketing|ROSCon-Content|Roadmap|Releases|Feature-Ideas"
    actions:
      backport:
        branches:
<<<<<<< HEAD
          - humble
          - foxy
=======
          - foxy
          - dashing
>>>>>>> 5884b736042684e34db58d74fabbabd321bdfafa

  - name: backport at reviewers discretion
    conditions:
      - base=rolling
      - "label=backport-all"
    actions:
      backport:
        branches:
<<<<<<< HEAD
          - humble
          - foxy

  - name: backport to humble at reviewers discretion
    conditions:
      - base=rolling
      - "label=backport-humble"
    actions:
      backport:
        branches:
          - humble
=======
          - foxy
          - dashing
>>>>>>> 5884b736042684e34db58d74fabbabd321bdfafa

  - name: backport to foxy at reviewers discretion
    conditions:
      - base=rolling
      - "label=backport-foxy"
    actions:
      backport:
        branches:
          - foxy
<<<<<<< HEAD
=======

  - name: backport to dashing at reviewers discretion
    conditions:
      - base=rolling
      - "label=backport-dashing"
    actions:
      backport:
        branches:
          - dashing
>>>>>>> 5884b736042684e34db58d74fabbabd321bdfafa
